### ISSUE TITLE
libvmm's SDDF submodule is out of date

### ISSUE THREAD

**Issue by khconfiware** [au-ts/libvmm#133]
In commit "Rename serial size fields to capacity" (9f85702467d52e7f5f6487b4f44f6392b8e9a9c1), on the SDDF repository, the field "size" was changed to "capacity" in serial_queue_handle in file `sddf/include/sddf/serial/queue.h` line 29.

The current SDDF submodule in libvmm the field is still called size. But if you change the submodule to a SDDF submodule which is on the newest commit, the file `libvmm/src/virtio/console.c` does not build since you refer to the field "size" on line 143. 

Why the SDDF submodule in libvmm is not up to date with the newest commit i am not quite sure of. I would assume it would be on the newest commit, but it does not seem that way.

Maybe i have misunderstood something, but it seems to me like it is a mistake.

Also seems like #92 fixed the same problem for block.c, where this happens in console.c.

Thanks for the help :)

Kasper

**Comment by Ivan-Velickovic** [comment]
> Maybe i have misunderstood something, but it seems to me like it is a mistake.

The submodule pins a certain commit of sDDF so that everything still works, it does not automatically use the latest commit otherwise it would break whenever there is a breaking change in sDDF like there is now. We try to have libvmm use the latest version of sDDF but sometimes it gets a bit behind.

Fixed in https://github.com/au-ts/libvmm/pull/131.
